version: '3'
services:
  datajoint:
    build: .
    env_file: .env
    volumes:
      - ./notebooks:/notebooks
      - ./images:/images
      - .:/src/IBL-pipeline
      - ./data:/data
      - ~/.one_params:/root/.one_params
      - ./snapshots:/Figures_DataJoint_shortcuts
    ports:
      - "8888:8888"
